close all; clear;

% look for all the files named "testX.s2p"
% and open them as s-parameter objects in a list
fileprefix = "";
directory = pwd;

% Get a list of all files in the directory
files = dir(fullfile(directory, [fileprefix + '*.s2p']));
% Determine the number of files found
num_files = numel(files);

% Initialize a cell array to store the data from each file
sparamCell = cell(1, num_files);
figure;
for i = 1:num_files
    % Construct the filename
    obj = SParameterChannel('FileName',files(i).name,...
    'PortOrder', [1 2],...
    'MaxNumberOfPoles', 64,...
    'ErrorTolerance', -40,...
    'SampleInterval', 6.25e-12,...
    'StopTime', 80e-9,...
    'TxR',50,...
    'TxC',0.1e-12,...
    'TxAmplitude', 1.0,...
    'TxRiseTime', 40e-12,...
    'TxRTFactor', 0.6,...
    'RxR',50,...
    'RxC',0.2e-12,...
    'Signaling','single-ended',...
    'AggressorDefinition','same-load');
    t = obj.t;
    impulse = obj.ImpulseResponse;
    figure;
    plot(t,impulse);
end
hold off;